In [1]:
import re
import os
import pandas as pd
from io import StringIO
from sklearn.model_selection import train_test_split

In [14]:
# filename = 'ACAR556.csv'
for filename in os.listdir('./PJ_cleaned/'):
    if '.csv' in filename:
        print(filename)
        df = pd.read_csv(f'./PJ_cleaned/{filename}', sep='|', header=None)

        new_training_string = ""

        # print(df[2])
        # u_idx = 0
        messages = ["START"]
        for i in range(len(df)):
            if df.iloc[i][0] in filename:
                usr = "groomer"
            else:
                usr = "victim"
            
            msg = df.iloc[i][2]
            # usr = users[u_idx]
            if len(messages) > 10:
                hist = ';;'.join(messages[-10:])
            else:
                hist = ';;'.join(messages)

            if usr == 'groomer':
                new_training_string += f"{hist}|{usr}:{msg}\n"
            messages.append(f'{usr}:{msg}')

            # u_idx = not u_idx
#print(new_training_string)


file = open(f'./groomer_training_data.csv', 'w')
file.writelines(new_training_string)
file.close()

df2 = pd.read_csv('./groomer_training_data.csv', sep='|', header=None)
train, test = train_test_split(df2, test_size=0.1)
test.to_csv('./groomer_test.csv', sep='|')
train.to_csv('./groomer_train.csv', sep='|')

spongebob_giantdick.csv
arb1210.csv
jim_garvin56.csv
atonomous2000.csv
gmoney301981.csv
b080387.csv
the_donjuan02.csv
icouldspoilu.csv
jake905_1999.csv
flamningdonkeybutt.csv
kool_biker80.csv
jbird2000_95020.csv
wesleybrannen82.csv
vamale_692005.csv
alonzo403.csv
buick19722001.csv
aladiesmasseur.csv
likuososweet.csv
wocket2003.csv
donni1957_male.csv
va_breitling.csv
sphinx_56_02.csv
hotplushung.csv
goodbody1330.csv
netbuckeye.csv
parknride_469.csv
seanemdyoung.csv
latinhawk63.csv
can_i_rape_you_anally.csv
jteno72960.csv
blaggca.csv
corazon23456partio23456.csv
mrlvejones.csv
kenneth_forton.csv
rkline05.csv
nakzox.csv
chinaski818.csv
clitlicker42303.csv
wi11s_atm.csv
jim90020.csv
farzadboy2003.csv
latino_626.csv
yankees_9ers_dad.csv
hot95cobraguy.csv
drmz_1980.csv
abraxisreborn.csv
blindsey_01.csv
cal_xicano130.csv
centgaguy04.csv
desiredalex.csv
holdyoucloser2003.csv
tunnels12000.csv
hey_malen.csv
longbeachdude19.csv
dble_d1.csv
mikespikegetiingcrazytocu.csv
kinky_man_in_corona.csv
john_frady2006.csv
balin79.csv
dragon_2973.csv
elchiva8395020.csv
mikejardi.csv
sebastian_calif.csv
come_ride_and_chill_with_me.csv
spaki786.csv
briman31282.csv
marzain2002.csv
whittierlacumandbig.csv
mannbay2004.csv
tmceach2000.csv
hennessy1436.csv
artc68.csv
steven_duncil78.csv
mike_vestal69.csv
wellhungnwky.csv
samr125.csv
whittierwannado.csv
mandaringuy78.csv
kinkyjeff694u.csv
bendix632.csv
needinit1983.csv
budd44800.csv
westwoodkush.csv
jagjen2003.csv
bud448002.csv
asian_kreationz.csv
michaelmeyer2448.csv
magichands7777.csv
g8rman21.csv
bob10282001.csv
golfboi59.csv
daggers_of_passion.csv
i_8u_raw.csv
g_balthareddy.csv
edgesoccer22.csv
mani_dasa.csv
marc_00_48089.csv
liv2rydu10.csv
maken_do_692003.csv
yp_anthony_louisville_284.csv
atl_csd_7_kcusn_lexis_davis2000.csv
camaroz282006ss.csv
wow_you_like.csv
jack_doh12.csv
redneckraynor20.csv
gjk1352.csv
morg_stick.csv
the_third_storm.csv
rebal20032003.csv
freshfromthemachine.csv
norcal8guy.csv
nickpaul19802000.csv
singlemalestaynfit2000.csv
padre0572.csv
thenamestheygivearedumb.csv
jon_raven2000.csv
darkguyx31.csv
Develo_Arma.csv
sebastian_lavc.csv
gerald_white30627.csv
bluebentleydog.csv
ACAR556.csv
pickup_man87.csv
cmyc3vette.csv
i_smoke_alotta_weed.csv
mike_trucker2001.csv
alanp110.csv
persuasion2032.csv
sebastian_for_u.csv
ghost27_73.csv
letsgo212000.csv
vinnyblubinzburg.csv
youwantcomeandgetme2005.csv
jaysun28m.csv
toddb39.csv
a_latino_man559.csv
primitman.csv
skargakos.csv
working_loving_goodman.csv
lhofusa.csv
jstforfun007.csv
perangiyur.csv
antonio69_929.csv
importuner81.csv
kfrankhouse350z.csv
whiteboy562.csv
tattooedman73.csv
cowboy39461.csv
smk610.csv
ktech724.csv
teadyber.csv
mkrauss0460.csv
indianman76.csv
lovermangenuis.csv
ussoldier2281_lowcamaro97.csv
jon_buckland.csv
ikeman_04.csv
FirstAndGrand.csv
shaka_k2000.csv
victor_wells2002.csv
zigdog2k3.csv
nj_dom_4_f.csv
dragonhighlord19.csv
mack916.csv
kingspade1714.csv
fseminoles2008.csv
popogh64.csv
uchi_deshi2000.csv
jdmar74.csv
caspersc78.csv
m0g21sk.csv
rockstar9992003.csv
erickbigdick.csv
ballsac49829.csv
daddieforu.csv
truckboss005.csv
gca93066.csv
xclusivelyinit.csv
craigtraylor.csv
uncommansense2.csv
jackman_9682.csv
woodentaintboy.csv
teakadai_pandi.csv
thedragonreborn_30.csv
guy_from_mars83.csv
producerpaul2001.csv
dipoyoy.csv
nhbfullcontact21.csv
davekruz2003.csv
shi_guy_99.csv
tonezonenj.csv
sharkiesfin2000.csv
virgin18yearold.csv
perfect_buddy_ga.csv
construction1302.csv
phoenix89032.csv
mlchatellier.csv
mikeb44la2000.csv
fjk84412.csv
andaconda40.csv
hungforyung.csv
justmetoddray.csv
racine_guy22.csv
darkprince666_2006.csv
mikep37013.csv
hunglowilove69.csv
recon101_2000.csv
movieman2397.csv
big_dave5188.csv
bmichigan69.csv
soulkeepndaddy.csv
wl72971.csv
darthkaveli.csv
dan45_m_1.csv

In [29]:
df.head()

              0                      1                          2
0     dan45_m_1  (07/30/09 2:21:51 PM)  hi your nice looking girl
1  mistygray013  (07/30/09 2:22:06 PM)                     thanks
2     dan45_m_1  (07/30/09 2:22:20 PM)               your welcome
3  mistygray013  (07/30/09 2:23:02 PM)              whats ur asl?
4     dan45_m_1  (07/30/09 2:23:19 PM)               54/m/up noth

In [24]:
df2.head()

                                                   0                     1
0                                              START         victim:thanks
1         START;;victim:thanks;;groomer:your welcome  victim:whats ur asl?
2  START;;victim:thanks;;groomer:your welcome;;vi...     victim:im heather
3  START;;victim:thanks;;groomer:your welcome;;vi...        victim:14 f mi
4  START;;victim:thanks;;groomer:your welcome;;vi...             victim:ya

In [31]:
df2 = pd.read_csv('./groomer_training_data.csv', sep='|', header=None)
nan_rows = df2[df2[0].isnull()]
print(nan_rows)
print(df2.columns)

Empty DataFrame
Columns: [0, 1]
Index: []
Index([0, 1], dtype='int64')

In [15]:
# filename = 'ACAR556.csv'
for filename in os.listdir('./PJ_cleaned/'):
     if '.csv' in filename:
        # print(filename)
        df = pd.read_csv(f'./PJ_cleaned/{filename}', sep='|', header=None)

        new_training_string = ""

        # print(df[2])
        # u_idx = 0
        messages = ["START"]
        for i in range(1, len(df)):
            if df.iloc[i][0] in filename:
                usr = "groomer"
            else:
                usr = "victim"
            
            msg = df.iloc[i][2]
            # usr = users[u_idx]
            if len(messages) > 10:
                hist = ';;'.join(messages[-10:])
            else:
                hist = ';;'.join(messages)

            if usr == 'victim':
                new_training_string += f"{hist}|{usr}:{msg}\n"
            messages.append(f'{usr}:{msg}')

            # u_idx = not u_idx
#print(new_training_string)


file = open(f'./victim_training_data.csv', 'w')
file.writelines(new_training_string)
file.close()

In [16]:
df2 = pd.read_csv('./victim_training_data.csv', sep='|', header=None)
df2

                                                     0                      1
0                                                START          victim:thanks
1           START;;victim:thanks;;groomer:your welcome   victim:whats ur asl?
2    START;;victim:thanks;;groomer:your welcome;;vi...      victim:im heather
3    START;;victim:thanks;;groomer:your welcome;;vi...         victim:14 f mi
4    START;;victim:thanks;;groomer:your welcome;;vi...              victim:ya
..                                                 ...                    ...
386  victim:granpa got home;;groomer:oh;;groomer:ok...              victim:ok
387  groomer:ok cool;;groomer:he sleeping?;;victim:...              victim:no
388  victim:no;;victim:hes puttin his stuff away n ...      victim:i got 2 go
389  victim:hes puttin his stuff away n taking a sh...  victim:granpas comign
390  groomer:u want to see my cam;;victim:ok;;groom...             victim:bye

[391 rows x 2 columns]

In [28]:
nan_rows = df2[df2[0].isnull()]
print(nan_rows)

Empty DataFrame
Columns: [0, 1]
Index: []

In [17]:
train, test = train_test_split(df2, test_size=0.1)
test.to_csv('./victim_test.csv', sep='|')
train.to_csv('./victim_train.csv', sep='|')